name: daily_buddy
description: "An App to make list of to do list"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen : ^1.3.0
  flutter_svg: ^2.0.9
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  http: ^1.1.2
  intl: ^0.19.0
  fluttertoast: ^8.2.4
  logger: ^2.0.2+1
  flutter_slidable: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  get:
flutter:
  uses-material-design: true
  assets:
    - assets/splash.svg
    - assets/404.svg

